version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: social_support_db
    ports:
      - "5435:5432"  # <--- غيرنا الرقم ده
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpass
      - POSTGRES_DB=social_support
    volumes:
      - ./data/postgres_new:/var/lib/postgresql/data # <--- غيرنا اسم الفولدر عشان يعمل واحد جديد

  qdrant:
    image: qdrant/qdrant:latest
    container_name: social_support_vector_db
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage

  redis:
    image: redis:alpine
    container_name: social_support_queue
    ports:
      - "6379:6379"
